# Generated by Django 4.1.8 on 2023-04-07 23:32

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mesa', models.IntegerField()),
                ('lista_productos', djongo.models.fields.JSONField()),
            ],
        ),
    ]
